version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "crackers"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-htctamk2rpwj"
s3_prefix = "crackers"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
