AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  crackers

Globals:
  Function:
    Runtime: python3.9
    Timeout: 30
    Environment:
      Variables:
        CLIENTS_TABLE: !Ref ClientsTable

Resources:
  ClientsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: Number

  CreateClientFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: core/
      Handler: client.create_client
      # APIGateway Used as a trigger of this function - Events
      Events:
        CreateClients:
          Type: Api
          Properties:
            Path: /clients
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ClientsTable

  ReadClientFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: core/
      Handler: client.get_client
      # APIGateway Used as a trigger of this function - Events
      Events:
        ReadClients:
          Type: Api
          Properties:
            Path: /clients/{id}
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ClientsTable

Outputs:
  CreateCliensAPI:
    Description: "API Gateway Endpoint url for creating clients."
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage/clients"
  CreateClientFunction:
    Description: "Create client function ARN."
    Value: !GetAtt CreateClientFunction.Arn
  CreateClientFunctionIamRole:
    Description: "Create client function IAM ARN."
    Value: !GetAtt CreateClientFunctionRole.Arn