AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  crackers

  Sample SAM Template for crackers

Resources:
  CreateClientFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: core/
      Handler: client.create_client
      Runtime: python3.9
      # APIGateway Used as a trigger of this function - Events
      Events:
        CreateClients:
          Type: Api
          Properties:
            Path: /clients
            Method: POST

  ReadClientFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: core/
      Handler: client.get_client
      Runtime: python3.9
      # APIGateway Used as a trigger of this function - Events
      Events:
        ReadClients:
          Type: Api
          Properties:
            Path: /clients/{id}
            Method: GET

  ReadCardFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: core/
      Handler: app.read_card_handler
      Runtime: python3.9
